#!/usr/bin/env bash
# Generated by docgen for the GitHub Pages edition. Run --dry-run to review setup.
set -euo pipefail
sdk_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"
setup="$sdk_dir/node_modules/@voxgig/docgen/dist/admin/github-pages.js"
if [[ ! -f "$setup" ]]; then
  echo 'Install or update the .sdk dependencies to configure GitHub Pages.' >&2
  exit 1
fi
exec node "$setup" "$sdk_dir/.." "$@"
