// `mkdocs.yml` — GENERATED, not templated.
//
// Its `nav` names every page by path, so a templated one goes stale the
// moment an entity is added or an SDK installed. Same reason rust's
// `feature/mod.rs` is emitted from the model rather than shipped.

import { cmp, File, Content } from '@voxgig/sdkgen'

import { yamlString } from './utility_apidocs'


// One nav line, indented for a section. BOTH halves are quoted: the title
// because it is often the API author's own words, and the path because it is
// built from a name out of the same document — a colon in either silently
// remaps the entry to something mkdocs cannot find.
function navEntry(title: any, page: any): string {
  return '      - ' + yamlString(title) + ': ' + yamlString(page)
}


const Nav = cmp(function Nav(props: any) {
  const { model, docs, entities, targets, features } = props

  const info = model?.main?.kit?.info ?? {}

  File({ name: 'mkdocs.yml' }, () => {
    const lines: string[] = [
      '# Generated by @voxgig/docgen. Edits are overwritten — see',
      '# the `apidocs` item in your .sdk/model/docs/.',
      'site_name: ' + yamlString((info.title || model.Name || model.name) +
        ' documentation'),
    ]

    if ('' !== String(info.summary ?? '')) {
      lines.push('site_description: ' + yamlString(info.summary))
    }

    const url = docs?.site?.url

    if (null != url && '' !== url) {
      lines.push('site_url: ' + yamlString(url))
    }

    lines.push(
      '',
      'theme:',
      '  name: material',
      '  features:',
      '    - navigation.sections',
      '    - content.code.copy',
      '',
      'markdown_extensions:',
      '  - admonition',
      '  - tables',
      '  - pymdownx.highlight',
      '  - pymdownx.superfences',
      '  - pymdownx.tabbed:',
      '      alternate_style: true',
      '',
      'nav:',
      '  - Overview: index.md',
    )

    if (0 < entities.length) {
      lines.push('  - API:')
      for (const entity of entities) {
        lines.push(navEntry(entity.Name || entity.name,
          'api/' + entity.name + '.md'))
      }
    }

    if (0 < targets.length) {
      lines.push('  - SDKs:')
      for (const target of targets) {
        lines.push(navEntry(target.title || target.name,
          'sdks/' + target.name + '.md'))
      }
    }

    if (0 < features.length) {
      lines.push('  - Features:')
      for (const feature of features) {
        lines.push(navEntry(feature.title || feature.name,
          'features/' + feature.name + '.md'))
      }
    }

    // The project's OWN entries, last: `site.extra`, for pages written by
    // hand beside the generated ones.
    //
    // Accepting a setting and never reading it is worse than not offering it.
    // The model documented `extra` from the first commit, so a project that
    // set it got silence — and no way to tell whether its value was wrong or
    // the feature absent.
    //
    // The model narrows an entry to a page or a ONE-LEVEL section, which is
    // what makes this emittable without a YAML library.
    for (const entry of (docs?.site?.extra ?? [])) {
      const title = String(entry?.title ?? '')

      if ('' === title) {
        continue
      }

      const items = (entry?.items ?? []).filter((item: any) =>
        '' !== String(item?.title ?? '') && '' !== String(item?.page ?? ''))

      if (0 < items.length) {
        lines.push('  - ' + yamlString(title) + ':')
        for (const item of items) {
          lines.push(navEntry(item.title, item.page))
        }
      }
      else if ('' !== String(entry?.page ?? '')) {
        lines.push('  - ' + yamlString(title) + ': ' + yamlString(entry.page))
      }
    }

    Content(lines.join('\n') + '\n')
  })
})


export {
  Nav
}
