// `mkdocs.yml` — GENERATED, not templated.
//
// Its `nav` names every page by path, so a templated one goes stale the
// moment an entity is added or an SDK installed. Same reason rust's
// `feature/mod.rs` is emitted from the model rather than shipped.

import { cmp, File, Content } from '@voxgig/sdkgen'

import { yamlString } from './utility_apidocs'


const Nav = cmp(function Nav(props: any) {
  const { model, docs, entities, targets, features } = props

  const info = model?.main?.kit?.info ?? {}

  File({ name: 'mkdocs.yml' }, () => {
    const lines: string[] = [
      '# Generated by @voxgig/docgen. Edits are overwritten — see',
      '# the `apidocs` item in your .sdk/model/docs/.',
      'site_name: ' + yamlString((info.title || model.Name || model.name) +
        ' documentation'),
    ]

    if ('' !== String(info.summary ?? '')) {
      lines.push('site_description: ' + yamlString(info.summary))
    }

    const url = docs?.site?.url

    if (null != url && '' !== url) {
      lines.push('site_url: ' + yamlString(url))
    }

    lines.push(
      '',
      'theme:',
      '  name: material',
      '  features:',
      '    - navigation.sections',
      '    - content.code.copy',
      '',
      'markdown_extensions:',
      '  - admonition',
      '  - tables',
      '  - pymdownx.highlight',
      '  - pymdownx.superfences',
      '  - pymdownx.tabbed:',
      '      alternate_style: true',
      '',
      'nav:',
      '  - Overview: index.md',
    )

    if (0 < entities.length) {
      lines.push('  - API:')
      for (const entity of entities) {
        lines.push('      - ' + yamlString(entity.Name || entity.name) +
          ': api/' + entity.name + '.md')
      }
    }

    if (0 < targets.length) {
      lines.push('  - SDKs:')
      for (const target of targets) {
        lines.push('      - ' + yamlString(target.title || target.name) +
          ': sdks/' + target.name + '.md')
      }
    }

    if (0 < features.length) {
      lines.push('  - Features:')
      for (const feature of features) {
        lines.push('      - ' + yamlString(feature.title || feature.name) +
          ': features/' + feature.name + '.md')
      }
    }

    Content(lines.join('\n') + '\n')
  })
})


export {
  Nav
}
